language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install -D "@vuepress/plugin-search"
  - npm install -D markdown-it-task-lists
  - npm install
  - npm run build
  - printf "airship.tf\n" > .vuepress/dist/CNAME

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN 
  target-branch: gh-pages
  local-dir: .vuepress/dist
  on:
    branch: master
